name: CI
on:
  push: #Act on push event on main and develop branches
    branches:
      - main
      - develop
  schedule:
    - cron: '0 3 * * SUN' #At 03:00 on Sunday.

jobs:
  Build:
    strategy:
      matrix:
        os: [windows, macos, ubuntu]
        jvm_version: [8, 11, 14]
    runs-on: ${{ matrix.os }}-latest
    env:
      JAVA_VERSION: ${{ matrix.jvm_version }}
      OS: ${{ matrix.os }}
      TERM: dumb
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fetch tags #Fetch all tags from remote repository
        shell: bash
        run: git fetch --tags -f
      - name: Populate TAG and BRANCH environment variables
        shell: bash
        #Setup in the TAG and in BRANCH TAG environment variable
        run: |
          TAG=$(git describe --tags --exact-match HEAD || echo '')
          echo "Current tag is: '$TAG'"
          echo "TAG=$TAG" >> $GITHUB_ENV
          BRANCH=$([ -z "$TAG" ] && echo ${GITHUB_REF#refs/heads/} || echo $TAG)
          echo "Current branch is: '$BRANCH'"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
      # Install the JDK
      - uses: joschi/setup-jdk@v2.3.0
        with:
          java-version: ${{ matrix.jvm_version }}
      # Install additional packages, if are present some specific configurations.
      - name: Configure Linux
        shell: bash
        if: ${{ contains(matrix.os, 'ubuntu') }}
        run: |
          if [ -x .github/scripts/configure_linux ]; then
            .github/scripts/configure_linux
          fi
      - name: Configure MacOS X
        shell: bash
        if: ${{contains(matrix.os, 'macos')}}
        run: |
          if [ -f .github/scripts/configure_macos ]; then
            .github/scripts/configure_macos
          fi
      - name: Configure the Windows Pagefile
        if: ${{ contains(matrix.os, 'windows') }}
        uses: al-cheb/configure-pagefile-action@v1.2
      - name: Configure Windows
        shell: bash
        if: ${{ contains(matrix.os, 'windows') }}
        run: |
          if [ -f .github/scripts/configure_windows ]; then
            .github/scripts/configure_windows
          fi
      - name: Build
        shell: bash
        run: .github/build-steps/build.sh
      - name: Check
        shell: bash
        run: .github/build-steps/check.sh
       #Upload coverage report to Codecov by action "codecov/codecov-action@v1"
      - name: CodeCov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
  Build-Success:
    runs-on: ubuntu-latest
    needs: Build
   #If build success, create artifact and upload on GithubActions
    steps:
      - shell: bash
        run: touch ok
        #Action to upload artifact
      - uses: actions/upload-artifact@v2
        with:
          name: success
          path: ok
  CI-Complete:
    needs: Build-Success
    if: always()
    runs-on: ubuntu-latest
    #To complete CI pipeline, download artifact created previously.
    steps:
      #Action to download artifact
      - uses: actions/download-artifact@v2
        with:
          name: success
      - shell: bash
        run: '[ -f ok ]'
